image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Python project with dependencies
    init: |
      pip install -e .
      gp sync-done dependencies

  - name: Launch JupyterLab
    init: |
      gp sync-await dependencies
      pip install -r dev-requirements.txt
    # Inspiration: https://github.com/jupyterlab/jupyterlab/blob/a920f33/.gitpod.yml
    command: |
      jupyter lab --port 8888 \
        --ServerApp.IdentityProvider.token='' \
        --ServerApp.allow_origin='*' \
        --ServerApp.tornado_settings='{"headers": {"Content-Security-Policy": "frame-ancestors *"}}' \
        --no-browser

ports:
  - port: 8888
